# Generated by Django 3.0.5 on 2020-04-08 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200408_1109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='dpt_id',
        ),
        migrations.AddField(
            model_name='user',
            name='dpt',
            field=models.CharField(default='', max_length=255, unique=True, verbose_name='dpt'),
        ),
    ]
