# Generated by Django 3.0.5 on 2020-04-08 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0001_initial'),
        ('view_page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='group',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='dpt_store_code', to='groups.Group'),
        ),
        migrations.AddField(
            model_name='log',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='dpt_store_code', to=settings.AUTH_USER_MODEL),
        ),
    ]
