# Generated by Django 3.0.5 on 2020-04-08 17:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('view_page', '0003_auto_20200408_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='group',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='view_page', to='groups.Group'),
        ),
        migrations.AlterField(
            model_name='log',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='view_page', to=settings.AUTH_USER_MODEL),
        ),
    ]
