# Generated by Django 3.0.5 on 2020-04-10 20:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('view_page', '0004_auto_20200408_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='log_time',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
