# Generated by Django 3.0.5 on 2020-04-08 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dpt_code', models.CharField(default='', max_length=255, unique=True)),
                ('dpt_name', models.CharField(default='', max_length=255, unique=True)),
            ],
            options={
                'ordering': ['dpt_code'],
            },
        ),
    ]
